# Change these first
owner: hugomods # Your GitHub organization or username, where this repository lives
repo: site-status # The name of this repository

sites:
  - name: HugoMods (English)
    url: https://hugomods.com/
  - name: HugoMods (Simplified Chinese)
    url: https://zh-hans.hugomods.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hugomods.com
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/128204519?s=200&v=4
  name: HugoMods Status
  introTitle: "Third party Hugo modules and tools for building fast, modular and modern themes and static websites."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
